### ISSUE TITLE
Abillity to take a picture

### ISSUE THREAD

**Issue by gustavung** [Guaschman/Graphrec#3]

**Comment by Matlar** [comment]
Should be able/forced to crop the image to a standard size, so the neural network can expect a fixed standard size for all images.

**Comment by Matlar** [comment]
Regarding the size, my initial suggestion would be to simply let it be 28x28 pixels as it seems to work well for the MNIST-'hello world' example. That does not mean that we only let the user take a 28x28 image as we can simply scale it down.

**Comment by gustavung** [comment]
Agreed, but if we scale the image to this fixed pixel size, then the aspect ratio will be destroyed. Would this affect the evaluation process in any way?

**Comment by Matlar** [comment]
One idea is that when the user takes a photo there is a frame with the correct aspect ratio over the photo screen that the user can move around to select the part of the photo that actually contains the graph. See how you can do it in the default photo editing app for android as an example:

![graph_photo](https://cloud.githubusercontent.com/assets/12465896/25699083/09a39672-30c2-11e7-991b-6b5e54380fbd.png) ![graph_photo_crop_frame](https://cloud.githubusercontent.com/assets/12465896/25699094/0f515762-30c2-11e7-9996-ff5abf29f088.png)

**Comment by gustavung** [comment]
Ah, a very interesting solution to the problem. One problem with this is that the simplest way to implement image capturing is to reuse a camera app already installed on android. The installed camera app might not have this scaling feature. To implement this properly we have to create our own camera interface in that case.

**Comment by Matlar** [comment]
See this [comment](https://github.com/Guaschman/Graphrec/pull/28#discussion_r115056807)

**Comment by gustavung** [comment]
I'm sorry, this was an old comment which I forgot to remove. The old approach was to send the entire picture with the intent, but this was very unstable at best. The new method is to create a private temp image file and then pass a Uri with the intent instead. This has proven to be a very good approach!

**Comment by Matlar** [comment]
We should probably be able to close this now

**Comment by gustavung** [comment]
Completed in #28
