### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by gustavung** [Guaschman/Graphrec#5]

**Comment by gustavung** [comment]
I have an initial design proposal for the application UI:

The start view:
![start_view](https://cloud.githubusercontent.com/assets/654024/25852072/6a94e1f2-34c8-11e7-836a-a56ecdb54c93.png)

The camera view:
![camera_view](https://cloud.githubusercontent.com/assets/654024/25852094/779396aa-34c8-11e7-91a7-b007fa6af675.png)

Note that the grey area would represent the camera preview.

The result view:
![result_view](https://cloud.githubusercontent.com/assets/654024/25852129/91715652-34c8-11e7-9284-07391c93ec5a.png)

Feedback would be appreciated! @Matlar

**Comment by Matlar** [comment]
Looks clean and simple, however maybe we should add the name or some logo at the main screen and some kind of indication of what you actually are expected to do or what you should expect to happen as you take a photo. Maybe add some icon or short text solving this, e.g. "Evaluate graph"

**Comment by gustavung** [comment]
Agreed, I added some text in the starting screen. This is implemented in #34.
