### ISSUE TITLE
Create interface for server-app communication

### ISSUE THREAD

**Issue by Matlar** [Guaschman/Graphrec#7]
Create and establish an interface for the communication between the mobile app and the server.

**Comment by Matlar** [comment]
Since I will be using the Flask web framework I think we should let the server only handle POST requests, where the client can send an image to the server. In the response we could send the graph classification result. In conclusion:
* **Server**: Only handles POST requests
* **Client**: Can only send POST requests

**Comment by gustavung** [comment]
Agreed, it is better to use a higher level protocol such as HTTP instead of a lower level equivalent such as UDP/TCP sockets for such a simple problem.

**Comment by Matlar** [comment]
Fixed in #29
